%% Import data from text file.

% Auto-generated by MATLAB on 2014/04/12 16:59:39

%% Initialize variables.
filename = 'CosmicMutantExportIncFus_v68_210114.tsv';
delimiter = '\t';
startRow = 2;

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow-1, 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[2,8,15]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [2,8,15]);
rawCellColumns = raw(:, [1,3,4,5,6,7,9,10,11,12,13,14]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
CosmicMutantExportIncFusv68210114 = table;
CosmicMutantExportIncFusv68210114.Genename = rawCellColumns(:, 1);
CosmicMutantExportIncFusv68210114.HGNCID = cell2mat(rawNumericColumns(:, 1));
CosmicMutantExportIncFusv68210114.Samplename = rawCellColumns(:, 2);
CosmicMutantExportIncFusv68210114.Primarysite = rawCellColumns(:, 3);
CosmicMutantExportIncFusv68210114.Sitesubtype = rawCellColumns(:, 4);
CosmicMutantExportIncFusv68210114.Primaryhistology = rawCellColumns(:, 5);
CosmicMutantExportIncFusv68210114.Histologysubtype = rawCellColumns(:, 6);
CosmicMutantExportIncFusv68210114.MutationID = cell2mat(rawNumericColumns(:, 2));
CosmicMutantExportIncFusv68210114.MutationCDS = rawCellColumns(:, 7);
CosmicMutantExportIncFusv68210114.MutationAA = rawCellColumns(:, 8);
CosmicMutantExportIncFusv68210114.MutationDescription = rawCellColumns(:, 9);
CosmicMutantExportIncFusv68210114.Mutationzygosity = rawCellColumns(:, 10);
CosmicMutantExportIncFusv68210114.MutationNCBI36genomeposition = rawCellColumns(:, 11);
CosmicMutantExportIncFusv68210114.MutationGRCh37genomeposition = rawCellColumns(:, 12);
CosmicMutantExportIncFusv68210114.Pubmed_PMID = cell2mat(rawNumericColumns(:, 3));
%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans raw col numericData rawData row regexstr result numbers invalidThousandsSeparator thousandsRegExp me rawNumericColumns rawCellColumns R;